encryptionsalt: v1:yRIg3H53ZJc=:v1:5OWTHSH1XZ/wMki+:Cx7LKAreytowL2L2D02OhlA/Lu1ysg==
config:
  gcp:project: dalab-anton
  gcp:region: us-central1
  nanoclaw:zone: us-central1-a
  nanoclaw:machineType: e2-standard-2
  nanoclaw:diskSizeGb: "50"
  nanoclaw:githubToken:
    secure: v1:xYOZBzOPitQZIe8x:QfWYc+yi5fASnhZjXMJsNMb+qUYqoE1fn6xsyDHrnVN4CMdC6q+sf56fx6pTMpE+YaFD5buhQ2mmfvazMCMPP7ZYYWrQm1rfThPSxb5yLRcv8/BLxBeP3LnPXf5ahyP8Zal+g9Q6Lc1Gj6lTWA==
  nanoclaw:sshPrivateKey:
    secure: v1:Dls/NKn40mhkp2ZH:xwq1TRAb5gWCgBoD/GKQanf52cNjqBEDkyKj6HmCpfu0LGlWZY3//s4uOUQIQWoDLOenH8rOUTMlxvgwSKd/QCbB0SglrZRddAU8SV+2uStSVjR9lWd4ECnAtikIaM+QJwPeNd8DoCJ8LKBokmz2KUvzDrjbu3zuhy6Pm7DpzfzaPIrUikKRIH3118S6UkG+LoUXnOvuJUjeP4ckaDluvpEZP42+q5oqpWxXVtLONSYrqWMXaJF/lRv3md7LAdDQ2hyXTC+poWJSAdkdivBbqIvbtDUtqvcX2Z8amVge12xwfXCFHGiDxXMI3gaLidkC0z3LLYXaeDbC1ikuUcbzljvTYfsCUNxymccozkSsutvCuMuAZhb++1Ufv2FD803ybwHl90jve6QueX5abauRRau6f/lwLUfnHpsLA8CHDEdOz9WN6PUsHpXEzTRnwdau/vy4aBVWLyhUmBkGqBCWoS6l4y/fsZ+nvfqqjGRXBBLKd8bY+7IgTrEcacCL7es05bi6u9ZtezY9JeTw6vqzRShOAi2BMv3V4oEa52jaxfDGF8gbJ7D6Y6/0
  nanoclaw:envGithubToken:
    secure: v1:eZPNQ5TR5fx/dmUf:nNU1pLoMub2tePS4chX4acdURcoZ6X8472M4upzkYC6/VgOfqNeYqoUcZJrIUSaMV0i7svkEbgE=
  nanoclaw:claudeCodeOauthToken:
    secure: v1:pmoX6qaKtPzHgoCr:MhoR2Q1Pt0CHhSl6zoZoyvux1Lnc9TrJN95y+W2LnDvuBw0QcTxpm8RSpiQ6lcF1yX+/sd0z9mT/TVYHXW2tkY8l4IuH7dTPdA3WgxIpnQNtXUW3Hy6G+sCtVtqLzV9hAevZtA5dBJSoNI4nGjkwzRlnmxKg541/ICzZSA==
  nanoclaw:slackBotToken:
    secure: v1:WBcQU1azuRppfcUG:kyoqZAfjpbndDC3hCn01N8Ve00sBW2NoHRFfq9LoZneupkEH59DkbzsDD7LfTr9eX3iz/mUV3FkqjBFE/Ir1vPWrdot+AXuKy0o=
  nanoclaw:slackAppToken:
    secure: v1:lJbcxGXtv9iWMBpa:fcbaQsJZ7UoOD1p00PxVfKslwGbwAj0lTFZa0ouWTz+xT0n+10a2nM2zO3y4vGZifl/yjz/en1wsgw1i8xwck//Rc+wdldswAWnn+5XNO+c2hQPf+HemxWHVOCeOMsPHcH8nih1ohhw31ZhsD3yPXG2G
